"""migration name

Revision ID: 0201da9b27de
Revises: 79df8e4d7c88
Create Date: 2023-05-08 03:05:08.913612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0201da9b27de'
down_revision = '79df8e4d7c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
