"""migration name

Revision ID: e03aebefc58f
Revises: 0201da9b27de
Create Date: 2023-05-08 03:19:15.819628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03aebefc58f'
down_revision = '0201da9b27de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
